import popUp from './modules/popUp';
import anchorLinks from './modules/anchorLinks';
import topSlider from './modules/topSlider';
import sliderCarousel from './modules/sliderCarousel';
import accordeon from './modules/accordeon';
popUp();
anchorLinks();
topSlider();
sliderCarousel();
accordeon();
