import popUp from './modules/popUp';
import anchorLinks from './modules/anchorLinks';
import topSlider from './modules/topSlider';
import sliderCarousel from './modules/sliderCarousel';
import accordeon from './modules/accordeon';
import upArrow from './modules/upArrow';
import sendForm from './modules/sendForm';
import validateForm from './modules/validateForm';
sendForm();
upArrow();
popUp();
anchorLinks();
topSlider();
sliderCarousel();
accordeon();
validateForm();
